config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#signup'
  get 'signin' => 'users#signin'
  post 'login_session' => 'users#login_session'
  delete 'logout' => 'users#logout'
  resources :users, only: [:create]
  resource :ajax, controller: :ajax, only: [] do
    get :fetch_cities
  end
  resources :products do
    member do
      post :change_top_and_down
      post :change_discount
    end

    collection do
      post :ajax_del_product
      get :search_user
      post :fetch_products
    end
  end
  resources :uploaders, only: [:create]
  get 'pages/:type/:id' => "pages#show"
end

app/models/user.rb
class User < ActiveRecord::Base
	include Paperclip::Glue #头像上传
	include PrettyIdable
	# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 #  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
	# has_secure_password
 # 	before_create {generate_token(:auth_token)}
	# validates :email, :password_digest, presence: {:message => '不能为空！'}
 #  validates :username, :email, :realname, uniqueness: { message: "不能重复！", case_sensitive: false } #这块儿区分大小小
 #  validates :username, length: {minimum: 6, maximum: 12, message: "长度不合法！"}
  has_many :products
	GENDERS = {"男" => true, "女" => false}.invert
	validate :at_least_one_of_email_and_mobile

	# 双向关系 可以 user.product_products 得到这个人所有生产的产品  user.deliver_products 得到这个人所有配送的产品
  # has_many :product_products, foreign_key: :product_product_id, class_name: 'Product', dependent: :destroy
  # has_many :deliver_products, foreign_key: :deliver_product_id, class_name: 'Product', dependent: :destroy

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

	def self.search_by(term, limit = 10)
    self.where("username like ?", "#{term}%").limit(limit)
  end

  # 注册时手机号和邮箱至少填写一个
  
  def at_least_one_of_email_and_mobile
    if [self.mobile, self.email].all?(&:blank?)
      errors[:base] << "邮箱和手机号不能同时为空!"
    end
  end

  # enum的用法总结 如果usert里边儿有个列status,系统会自动创建三个status_1..的类方法，，类名.status_1就会找到所有satus_1=1的记录
  enum status: {status_1: 1, status_2: 2, status_3: 3}
  
end

app/controllers/users_controller.rb
# user_model
class UsersController < ApplicationController
  before_action :provinces, only: [:signup, :create, :login_session, :signup]

  # 注册页面
  def signup
    @user = User.new
  end

  # 登录页面
  def signin
  end

  # 实现登录功能
  def login_session
    user = User.where(username: params[:username])[0]
    if user #&& user.authenticate(params[:password])
      # session[:user_id] = user_id
      # if params[:remember_me]
      #   cookies.permanent[:auth_token] = user.auth_token
      # else
      #   cookies[:auth_token] = user.auth_token
      # end
      redirect_to products_path
    else
      render :signup
    end
  end

  # 实现退出功能
  # def logout
  #   #session[:user_id] = nil
  #   cookies.delete(:auth_token)
  #   redirect_to :root
  # end

  # 实现注册功能
  def create
    @user = User.new(user_params)
    if @user.save
      #cookies[:auth_token] = @user.auth_token
      render :signin, notice: '注册成功！'
    else
      render :signup, notice: '注册有误！'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :realname, :gender, :province, :city, :birthday, :detail_address, :password_digest, :avatar)
  end
  def provinces
    @provinces, @cities = CityInit.get_provinces
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/signin.html.erb
<%= render partial: 'layouts/header' %>
<p class="notice"><%= notice %></p>
<table class="grid_form"> 
	<%= form_tag '/login_session' do %>
		<tr>
			<th colspan="2">用户登录</th>
		</tr>

		<tr>
			<td><%= label_tag '用户名' %></td>
			<td><%= text_field_tag :username, params[:name], placeholder: "请输入昵称/密码" %></td>
		</tr>

		<tr>
			<td><%= label_tag '密码' %></td>
			<td><%= password_field_tag :password, params[:password] %></td>
		</tr>

		<tr>
			<td colspan="2" class="button">
				<%= submit_tag '登录' %>
			</td>
		</tr>

	<% end %>
</table>
<%= render partial: 'layouts/footer' %>

app/views/users/signup.html.erb
<%= render partial: 'layouts/header' %>
<table class="grid_form">	
	<%= form_for @user, html: { multipart: true } do |f| %>

		<tr>
			<th colspan="2">用户注册</th>
		</tr>
		<tr>
			<td class="field"><b>*</b>用户昵称:</td>
			<td><%= f.text_field :username %></td>
		</tr>

		<tr>
			<td class="field"><b>*</b>Email:</td>
			<td><%= f.text_field :email %></td>
		</tr>

		<tr>
			<td class="field">名字:</td>
			<td><%= f.text_field :realname %></td>
		</tr>

		<tr>
			<td class="field">性别:</td>
			<td>
				<%= radio_button('user','gender','男') %>&nbsp; 男
				<%= radio_button('user','gender','女') %>&nbsp; 女 
			</td>
		</tr>

		<tr>
			<td class="field"><b>*</b>密码:</td>
			<td>
				<%= f.password_field :password_digest %>
			</td>
		</tr>

		<tr>
			<td class="field"><b>*</b>确认密码:</td>
			<td>
				<%= f.password_field :password_confirmation %>
			</td>
		</tr>

		<tr>
			<td class="field">地址:</td>
			<td>
				<%= f.select :province, @provinces.collect {|pro| [pro.name, pro.code]} %> &nbsp;&nbsp;
				<%= f.select :city, @cities.collect {|city| [city.name, city.code]} %>
			</td>
		</tr>

		<tr>
			<td class="field">出生日期:</td>
			<td>
				<%= f.date_field :birthday %>
			</td>
		</tr>

		<tr>
			<td class="field">详细地址:</td>
			<td>
				<%= f.text_area :detail_address, cols: "40", rows: "6" %>				
			</td>
		</tr>

		<tr>
			<td class="field">头像:</td>
			<td>
				<%= f.file_field :avatar %>
			</td>
		</tr>

		<tr>
			<td colspan="2" class="button">
				<%= f.submit '注册' %>&nbsp;&nbsp;
				<%= link_to '已注册直接登录', signin_path %>
			</td>
		</tr>

	<% end %>
</table>
<%= render partial: 'layouts/footer' %>
<script>
 $(function(){
   $("#user_province").change(function(){
     $.getScript('/ajax/fetch_cities?province_id=' + $(this).val());
   });
 });
</script>