config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#signup'
  get 'signin' => 'users#signin'
  post 'login_session' => 'users#login_session'
  delete 'logout' => 'users#logout'
  resources :users, only: [:create]
  resource :ajax, controller: :ajax, only: [] do
    get :fetch_cities
  end
  resources :products do
    member do
      post :change_top_and_down
      post :change_discount
    end

    collection do
      post :ajax_del_product
      get :search_user
      post :fetch_products
    end
  end
  resources :uploaders, only: [:create]
  get 'pages/:type/:id' => "pages#show"
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :type
	belongs_to :user
  validate :describtion_validates
  validates :name, presence: { message: "不能为空！" },
            uniqueness: { message: "不能重复！" },
            length: { minimum: 2, maximum: 20, message: "长度不正确[建议长度2-20]" }

	# 有命名空间
	# belongs_to :sender_staffer, class_name: "Admin::Staffer", foreign_key: :sender_staffer_id #生产者
  # belongs_to :audit_staffer, class_name: "Admin::Staffer", foreign_key: :audit_staffer_id #送货员

  # 无命名空间 product.product_user/product.product.deliver 得到固定产品的生产者和配送者
  # belongs_to :product_user, class_name: :User, foreign_key: :product_user_id #生产者
  # belongs_to :product_deliver, class_name: :User, foreign_key: :product_deliver_id #送货员

	DISCOUNT = { false => "没有折扣", true => "有折扣" } # 默认是有折扣的
  TOP_AND_DOWN = { false => "已下架", true => "未下架" } # 默认是未下架

  # 按照日期进行搜索
  scope :created_at_gte, -> (date_str) { date_str.present? ? where('created_at >= ?', Date.parse(date_str)) : all }
  scope :created_at_lte, -> (date_str) { date_str.present? ? where('created_at <= ?', Date.parse(date_str) + 1) : all }

  # 统计不同类型的产品数量
  scope :type_count, -> (type_id){where("type_id = ?", type_id).count }
  # scope :search, -> (search) { where('"products"."name" LIKE ?', "#{sanitize_sql_like(search)}%") }

  # 对录入产品信息做个验证
  def describtion_validates
    self.errors.add(:describtion, "产品描述输入有误，请重新录入！") if self.describtion.present? && !self.describtion.include?("值得信任！")
  end

  # 验证手机号是否输入有误
  # validate :mebile_validates
  # def mebile_validates
  #   mobile_errors = []
  #   if self.receive_tel.present?
  #     mobiles = self.receive_tel.split("\r\n") 录入时必须换行
  #     mobiles.uniq.each do |mobile|
  #       mobile_errors << /^1[0-9]{10}$/.match(mobile)
  #     end
  #     self.errors.add(:receive_tel, "手机格式输入有误，请重新录入！") if mobile_errors.include?(nil)
  #   end
  # end

  # scope 用法
  #scope :area, -> {where("id > 2")} #scope 没有参数的
  #scope :get_type, -> (product_id){where("id = ?",product_id)}
  #Product::scope_name 调用方式

  #scope :sort_desc, -> { order(id: :desc) }
  # scope :deleted, -> { where deleted: true }
  # scope :undeleted, -> { where deleted: false }
  # scope :top, -> { where commentable_ids: nil }
  # scope :created_gte, ->(time) { where("created_at >= ?", time) }
  # scope :id_lt, -> (id) { where("id < ?", id) if id > 0 }

  # 回调用法

  # before_save :change_count, if: :discount  条件回调
  # def change_count
  #   # 如果是有折扣的话，然后做另外的处理(其它回调方法 的用法都一样)
  # end

  # after_initialize :new_product  初始化回调
  # def new_product
  #   # 初始化时候出发这个回调(读取/new)
  # end

  # 在这儿做属性的处理的话，在查询的时候，读取对象.属性的时候会调用这个方法，默认会去找这个属性
  # def price
  #   super || 0.0
  # end

  #遍历的时候给每个对象的describtion属性add一条附加信息
  # def describtion
  #   super + "附加信息"
  # end

  # 导入导出文件
  class << self
    def import_c_name(file)
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        bs = find_by(id: row["id"]) || find_by(name: row["name"])
        if bs
          bs.attributes = row.to_hash.slice("name")
          bs.save!
        else
          # 打logo message
          logger.info("ERROR: cannot find name by name=#{row['name']}")
        end
      end
    end

    def open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path)
      when '.xlsx' then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

    def to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |bs|
          csv << bs.attributes.values_at(*column_names)
        end
      end
    end
  end


end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
	has_many :production
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  #skip_before_action :verify_authenticity_token # 防止cfrs 攻击(from表单post提交时会遇到这种状况)
	before_action :get_product, only: [:edit, :show, :destroy, :update, :change_top_and_down, :change_discount]
	before_action :get_type, only: [:new, :create, :edit, :update, :show, :index]
	before_action :get_user, only: [:new, :create, :edit, :update, :show, :index]
	before_action :get_product_user, only: [:index]

  caches_page :show

  # 批量加标题
  # before_action only: [:show, :invite] do
  #   @page_title = "邀好友，得奖励"
  #   @price = UserInviteLog::RULE.price
  # end
	
	def index
    @page_title = "产品集合"
		@q = Product.ransack(params[:q])
    @q = Product.search('%_%')
		@q = Product.created_at_gte(params[:created_at_gteq]).created_at_lte(params[:created_at_lteq]).search(params[:q])
		@products = @q.result.paginate(page: params[:page], per_page: 5).order('id DESC')
		@products = @products.where(type_id: params[:type_id]) if params[:type_id].present? #点击不同产品类型找到相关的产品
    # 解决英文下划线问题(ransack存在的问题)
    # ChannelCode.where("code like '%\\_%'").count 需要两个转义字符

	# respond_to do |format|
  #   format.html 
  #   format.csv { send_data @base_stocks.to_csv }
  #   format.xls { send_data @base_stocks.to_csv(col_sep: "\t") }
  # end
	end

	def new	
		@product = Product.new
	end

	def edit
	end

	def update
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def fetch_products
  	@productss = Product.where(type_id: params[:type_id])
    #render :aaa #fetch_products  (js/html)模版
  end

  # 改成ajax批量删除
	# <%= link_to '删除', p, method: :delete, data: {confirm: "你确定删除吗？"} %>
	# def destroy
  #   @product.destroy
  #   redirect_to products_path
	# end

	def create
		@product = Product.new(product_params)
	  if @product.save
	  	redirect_to products_path
	  else
	  	render :new
		end
	end

	# 导入csv, xls, xlsx
	def import_c_name
    if !params[:file].nil?
      begin
        BaseStock.import_c_name(params[:file])
        message = "导入成功"
      rescue Exception => e
        message = "导入失败，请确认文件类型为csv、xls或xlsx"
      end
    else
      message = "请选择文件"
    end
    redirect_to admin_base_stocks_path, notice: message
  end

	
  # def create
  #    @forbidden_name = ForbiddenName.create(word: params[:word].to_s.strip)
  #    notice = @forbidden_name.valid? ? "创建成功" : "已存在"
  #    redirect_to admin_forbidden_names_path, notice: notice
  #  end

	def change_top_and_down
		@product.top_and_down? ? @product.update(top_and_down: false) : @product.update(top_and_down: true)
    redirect_to :back
	end

	def change_discount
		@product.discount? ? @product.update(discount: false) : @product.update(discount: true)
    redirect_to :back
	end

	def ajax_del_product
		params[:ids].split(",").each{|id|
      m = Product.find(id).destroy
    }
    render text: "ok"
	end

	def search_user
    users = User.search_by(params[:q], 5).map{|u| u.attributes.slice("id", "username")}
    render json: {users: users, q: params[:q]}
	end

	def show
    @page_title = "产品明细"
		@product.increment!(:views_count)
	end

	private
	def product_params
		params.require(:product).permit(:name, :price, :discount, :top_and_down, :product_date, :type_id, :image, :describtion, :user_id)
	end

	def get_product
    @product ||= Product.find(params[:id])
  end

  def get_type
  	@types = Type.pluck("name", "id")
  end

  def get_user
    @users = User.pluck("username", "id")
  end

  def get_product_user
  	@product_user = params[:q].present? && params[:q][:user_id_eq].present? ? User.where(id: params[:q][:user_id_eq]).pluck(:id, :username).flatten : []
  end
end

app/views/products/_form.html.erb
<%= render 'layouts/header' %>
<span class="title_right">
  <%= link_to "返回列表", products_path %>
</span>
<%= form_for @product do |f| %>
<table class="grid_form">
  <tbody>
    <tr>
      <td class="field"><b>*</b>名称:</td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>价格:</td>
      <td>
        <%= f.text_field :price %>
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>折扣:</td>
      <td>
        <%= radio_button("product", "discount", true) %>&nbsp;是&nbsp;&nbsp;
        <%= radio_button("product", "discount", false) %>&nbsp;否
        </td>
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>下架:</td>
      <td>
        <%= radio_button("product", "top_and_down", false) %>&nbsp;是&nbsp;&nbsp;
        <%= radio_button("product", "top_and_down", true) %>&nbsp;否
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>产品类型:</td>
      <td>
        <%= f.select :type_id, options_for_select(@types, params[:type_id]) %>
      </td>
    </tr>
    <tr>
      <td class="field">生产者:</td>
      <td>
        <%= f.select :user_id, options_for_select(@users, params[:user_id]) %>
      </td>
    </tr>
    <tr>
      <td class="field">上传图片:</td>
      <td>
        <%= f.text_field :image, size: 20 %>
        <input type="button" id="upload_common_file_btn" value="上传图片"/>
        <div>
          <a target="_blank" href="" id="upload_img_a_link"><img src="" id="upload_img" style="max-height:100px"/></a>
        </div>
      </td>
    </tr>
    <tr>
      <td class="field">产品描述:</td>
      <td>
        <%= f.text_area :describtion, size: "50x10" %>
      </td>
    </tr>
    <tr>
      <td class="field"></td>
      <td>
        <%= f.submit params[:action] == "edit" ? "修改数据" : "新建数据" %>
      </td>
    </tr>
  </tbody>
</table>
<% end -%>
<%= render 'layouts/footer' %>
<script type="text/javascript">
  $("#upload_common_file_btn").uploader({url_field_id: "product_image", a_link_id: "upload_img_a_link", image_show_id: "upload_img"});
</script>

app/views/products/_import_and_export.html.erb
<div class="box">
  <div class="box-item pull-left">
    <%= form_tag(import_c_name_admin_base_stocks_path, class: "form-inline", role: "form", multipart: true) do %>
        <%= file_field_tag 'file', class: "form-control" %>
      <%= submit_tag "导入", class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="box-item pull-left">
  导出: <%= link_to "CSV", admin_base_stocks_path(params.merge(format: :csv))%> | <%= link_to "XLS", admin_base_stocks_path(params.merge(format: :xls))%>
  </div>
  <div class="clear"></div>
</div>

app/views/products/_search_form.html.erb
<div class="box">
	<%= search_form_for @q do |f| %>
	  <%= f.text_field :name_cont, placeholder: '请输入产品名称' %>
		<%= f.select :type_id_eq, options_for_select(@types, params[:type_id]) %>
    <%= f.select :id, options_for_select(@products.collect{|product| [product.name, product.id]}) %>
		<%= text_field_tag :created_at_gteq, params[:created_at_gteq], class: "datetimepicker", placeholder: "入库时间大于", "data-date-format" => "yyyy-mm-dd" %>
    ~	
    <%= text_field_tag :created_at_lteq, params[:created_at_lteq], class: "datetimepicker", placeholder: "入库时间小于", "data-date-format" => "yyyy-mm-dd" %>
  	<select style="width: 12%" class="product_user_search" name="q[user_id_eq]" id="producter"/>
    <input type="button" value="重置" id="user_clear">&nbsp;&nbsp;
    <%= f.submit "搜索" %>
 	<% end %>
  <% @types.each do |type| %>
      <a href="/products?type_id=<%= type[1] %>"><%= type[0] %>(<%= Product.type_count(type[1]) %>)</a>
    <% end %>
</div>

app/views/products/edit.html.erb
<%= render partial: "form" %>

app/views/products/fetch_products.js.erb
$("#q_id").empty();

<% if @stafferss.blank? %>
  $("#q_id").append("<option value=''>暂无产品</option>");
<% end %>

<% @productss.each do |product| %>
  $("#q_id").append("<option value='<%= product.name %>'><%= product.name %></option>");
<% end %>

app/views/products/form.html.erb
<%= form_for @product do |f| %>
<table class="grid_form">
  <tbody>
    <tr>
      <td class="field"><b>*</b>名称:</td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>价格:</td>
      <td>
        <%= f.text_field :price %>
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>折扣:</td>
      <td>
        <%= radio_button("product", "discount", true) %>&nbsp;是&nbsp;&nbsp;
        <%= radio_button("product", "discount", false) %>&nbsp;否
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>下架:</td>
      <td>
        <%= radio_button("product", "top_and_down", true) %>&nbsp;是&nbsp;&nbsp;
        <%= radio_button("product", "top_and_down", false) %>&nbsp;否
      </td>
    </tr>
    <tr>
      <td class="field"><b>*</b>产品类型:</td>
      <td>
        
      </td>
    </tr>
    <tr>
      <td class="field"></td>
      <td>
        <%= f.submit params[:action] == "edit" ? "修改数据" : "新建数据" %>
      </td>
    </tr>
  </tbody>
</table>
<% end -%>

app/views/products/index.html.erb
<%= javascript_include_tag  "/javascripts/datetimepicker/WdatePicker.js" %>
<%= render 'layouts/header' %>
	<%= will_paginate @products %>
	<span class="title_right">
    <%= link_to "添加数据", new_product_path %>
  </span>
  <%= render 'search_form' %>
  <%= page_info(@products) %>
	<table class="grid_form">
		<tr>
      <td colspan="13" style="text-align:right;">
        <a style="color:red !important;" href="javascript:" onclick="get_checkbox()">删除</a>
      </td>
    </tr>
		<tr>
			<th>
        <input type="checkbox" class="top_tree">
      </th>
			<th>ID</th>
			<%= content_tag :th, sort_link(@q, :name, '名称') %>
			<%= content_tag :th, sort_link(@q, :price, '价格') %>
			<th>是否有折扣</th>
			<th>上下架</th>
			<th width="20%">入库时间</th>
			<th>类型</th>
			<th>生产者</th>
			<th>产品图片</th>
			<th>产品描述</th>
			<th>访问次数</th>
			<th width="16%">操作</th>
		</tr>
		<% @products.each do |p| %>

			<tr id="check_<%= p.id %>">
				<td width="20px;">
          <input type="checkbox" class="bottom_tree" value="<%= p.id %>">
        </td>
				<td><%= p.id %></td>
				<td><%= p.name %></td>
				<td><%= p.price %></td>
				<td><%= Product::DISCOUNT[p.discount] %></td>
				<td><%= Product::TOP_AND_DOWN[p.top_and_down] %></td>
				<td><%= p.created_at.to_s %></td>
				<td><%= p.type.try(:name) %></td>
				<td><%= p.user.try(:username) %></td>
				<td>
					<%= p.image.present? ? image_tag(p.image, width: 100, height: 100) : "暂无图片！" %>
				</td>
				<td class="describtion"><%= p.describtion %></td>
				<td><%= p.views_count.to_i %></td>
				<td class="action">
          <%= link_to '详情', p %>
          <%= link_to '编辑', [:edit, p] %>
          <%= link_to p.top_and_down? ? "下架" : "上架", change_top_and_down_product_path(id: p.id), method: :post, data: {confirm: p.top_and_down? ? "确定下架吗?" : "确定上架吗?"} %>
          <%= link_to p.discount? ? "取消活动" : "搞活动", change_discount_product_path(id: p.id), method: :post, data: {confirm: p.discount? ? "确定取消吗?" : "确定设置吗?"}%>
				</td>
			</tr>
		<% end %>
		<%= blank_table(13) if @products.blank? -%>
	</table>	
<%= render 'layouts/footer' %>
<%= will_paginate @products %>
<script type="text/javascript">

	$(function(){
		// 初始化select2里边儿的值
	  $("#user_clear").hide();
	  var product_user = "<%= @product_user %>"
	  if (product_user.length > 2) {
	    $("#user_clear").show();
	    var user_id = "<%= @product_user[0] %>"
	    var user_name = "<%= @product_user[1] %>"
	    $("select[name='q[user_id_eq]']:eq(0)").append("<option value="+user_id+"></option>"); 
	    $("select[name='q[user_id_eq]']:eq(0)").select2("val", user_id)
	    $("#producter").next().children().children().children().first().get(0).innerHTML = user_name

	    $("#user_clear").click(function(){
	      $("select[name='q[user_id_eq]']:eq(0)").select2("val", "")
	      $("#producter").next().children().children().children().first().get(0).innerHTML = "发送者"
	    });
	  }

	  $("#q_type_id_eq").change(function(){
       $.post('/products/fetch_products?type_id=' + $(this).val());
     });
	});

 // 生产者
$(".product_user_search").select2({
  placeholder: "生产者",
  ajax: {
    url: "/products/search_user",
    dataType: 'json',
    delay: 300,
    data: function(params){
      return {
        q: params.term
      };
    },
    processResults: function (data, page) {
      return {
        results: data.users
      };
    }
  },
  templateResult: formatUser, //显示查询结果
  templateSelection: formatProducterSelection, //显示选中的对象
  escapeMarkup: function (markup) { return markup; }
});

function formatUser (user) {
  if (user.loading) return user.text; // 返回正在加载数据
  var markup = "<div style='float:center;color:#4F4F4F;'>"+user.username+"</div> " 
  return markup;
}

function formatProducterSelection (producter) {
  if (producter.username == undefined){
    return "生产者";
  } else {
    return producter.username;
  }
}

</script>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<%= render 'layouts/header' %>
	<span class="title_right">
    <%= link_to "返回列表", products_path %>
  </span>
	<table class="grid_form">
		<tr>
			<td class="field">产品名称:</td>
			<td><%= @product.name %></td>
		</tr>

		<tr>
			<td class="field">价格¥:</td>
			<td><%= @product.name %></td>
		</tr>

		<tr>
			<td class="field">是否下架:</td>
			<td><%= Product::DISCOUNT[@product.discount] %></td>
		</tr>

		<tr>
			<td class="field">折扣:</td>
			<td><%= Product::TOP_AND_DOWN[@product.top_and_down] %></td>
		</tr>

		<tr>
			<td class="field">入库日期:</td>
			<td><%= @product.created_at.to_s %></td>
		</tr>

		<tr>
			<td class="field">产品类型:</td>
			<td><%= @product.type.try(:name) %></td>
		</tr>

		<tr>
			<td class="field">生产者:</td>
			<td><%= @product.user.try(:username) %></td>
		</tr>

		<tr>
			<td class="field">图片:</td>
			<td><%= @product.image.present? ? image_tag(@product.image, width: 200, height: 200) : "暂无图片！" %><br/></td>
		</tr>

		<tr>
			<td class="field">产品描述:</td>
			<td><%= @product.describtion %><br/></td>
		</tr>
	</table>
<%= render 'layouts/footer' %>